import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The guide sidebar is generated from the section folders under docs/ (see
// sidebarItemsGenerator in docusaurus.config.ts, which leaves out cli/ and
// api/: they have their own sidebars and navbar entries). Each folder's
// _category_.json sets its position and label; the group numbers (01, 02…)
// are drawn by the theme from that order.
const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: '.'}],
  cli: [{type: 'autogenerated', dirName: 'cli'}],
  api: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
